Repository pyfar/sofar, pull requests merged in 2025-04, with the labels that each got.

#120 Update github workflows
  .github/workflows/has_label.yml
  .github/workflows/has_version_milestone.yml
Labels: CI

#122 sofar: Deprecate Sofa.info
  sofar/sofa.py
  tests/test_deprecations.py
  tests/test_sofa.py
Labels: feature

#125 apply cookiecutter
  .github/ISSUE_TEMPLATE.md
  .github/workflows/has_label.yml
  .github/workflows/has_version_milestone.yml
  docs/conf.py
  pyproject.toml
Labels: documentation
